stages:
  train:
    cmd: python productivity_predictor/src/training/train_model.py

    deps:
      - src/training/train_model.py
      - data/raw/productivity_data.csv
      - params.yaml
    outs:
      - models/
    metrics:
      - mlruns/  # optional — only if you log custom metrics elsewhere

